export const PROJECT_TIERS = {
  basic: {
    key: "basic",
    productKey: "project-basic",
    name: "Basic",
    label: "Automated short",
    priceUsd: 14.99,
    priceCents: 1499,
    sourceMinutes: 10,
    finalSeconds: 60,
    revisions: 1,
    outputVariants: 1,
    resolution: "1080p",
    description: "A focused short edit with cleanup, captions, music matching, and one draft.",
  },
  plus: {
    key: "plus",
    productKey: "project-plus",
    name: "Plus",
    label: "Creator production",
    priceUsd: 44.99,
    priceCents: 4499,
    sourceMinutes: 30,
    finalSeconds: 300,
    revisions: 2,
    outputVariants: 3,
    resolution: "1080p",
    description: "Story planning, animated captions, B-roll direction, and social format variants.",
  },
  premium: {
    key: "premium",
    productKey: "project-premium",
    name: "Premium",
    label: "Commercial production",
    priceUsd: 129.99,
    priceCents: 12999,
    sourceMinutes: 60,
    finalSeconds: 600,
    revisions: 2,
    outputVariants: 3,
    resolution: "4K",
    description: "Advanced narrative planning, 4K delivery, brand rules, generated media allowance, and human QA.",
  },
} as const;

export type ProjectTier = keyof typeof PROJECT_TIERS;

export const STYLE_DIRECTIONS = [
  {
    slug: "cinematic",
    title: "Cinematic narrative",
    shortLabel: "Cinematic",
    description: "Measured pacing, shaped contrast, atmospheric sound, and story-led cuts.",
    meta: ["Narrative", "Film grain", "Atmospheric"],
    position: "0% 0%",
    category: "Story" as const,
    featured: true,
    defaultMood: "emotional",
    defaultPace: "smooth-cinematic",
    defaultColorGrade: "moody",
  },
  {
    slug: "energetic",
    title: "Kinetic action",
    shortLabel: "Energetic",
    description: "Impact-driven cuts, motion accents, speed ramps, and high-energy timing.",
    meta: ["Action", "Beat sync", "Motion"],
    position: "50% 0%",
    category: "Social" as const,
    featured: true,
    defaultMood: "energetic",
    defaultPace: "fast-cuts",
    defaultColorGrade: "high-contrast",
  },
  {
    slug: "product",
    title: "Luxury product",
    shortLabel: "Luxury product",
    description: "Tactile detail, controlled highlights, and clean benefit-first composition.",
    meta: ["Product", "Macro", "Premium"],
    position: "100% 0%",
    category: "Brand" as const,
    defaultMood: "premium",
    defaultPace: "balanced",
    defaultColorGrade: "luxury-gold",
  },
  {
    slug: "documentary",
    title: "Human documentary",
    shortLabel: "Documentary",
    description: "Natural performance, honest pacing, and unobtrusive editorial structure.",
    meta: ["Interview", "Natural", "Story"],
    position: "0% 100%",
    category: "Story" as const,
    defaultMood: "calm",
    defaultPace: "balanced",
    defaultColorGrade: "natural",
  },
  {
    slug: "corporate",
    title: "Editorial corporate",
    shortLabel: "Clean corporate",
    description: "Architectural framing, credible typography, and confident information flow.",
    meta: ["Brand", "B2B", "Clean"],
    position: "50% 100%",
    category: "Brand" as const,
    defaultMood: "professional",
    defaultPace: "balanced",
    defaultColorGrade: "natural",
  },
  {
    slug: "social-media",
    title: "Creator social",
    shortLabel: "Creator social",
    description: "Immediate hooks, platform-native framing, and caption-safe composition.",
    meta: ["Vertical", "Hook", "Captions"],
    position: "100% 100%",
    category: "Social" as const,
    defaultMood: "energetic",
    defaultPace: "viral-short-form",
    defaultColorGrade: "bright",
  },
] as const;

export type StyleSlug = (typeof STYLE_DIRECTIONS)[number]["slug"];

export const PURPOSES = [
  "Wedding",
  "Graduation",
  "Birthday",
  "Business promo",
  "Product advertisement",
  "YouTube video",
  "TikTok / Reels / Shorts",
  "Podcast clip",
  "Real estate",
  "Restaurant / food promo",
  "Travel vlog",
  "Education / course",
  "Gaming highlight",
  "Family memory",
  "Memorial / tribute",
  "Other",
] as const;

export const MOODS = [
  ["romantic", "Romantic"],
  ["professional", "Professional"],
  ["energetic", "Energetic"],
  ["calm", "Calm"],
  ["emotional", "Emotional"],
  ["inspirational", "Inspirational"],
  ["premium", "Premium"],
  ["happy", "Happy"],
  ["nostalgic", "Nostalgic"],
  ["dramatic", "Dramatic"],
  ["soft", "Soft"],
  ["powerful", "Powerful"],
] as const;

export const PACES = [
  ["slow-emotional", "Slow and emotional"],
  ["balanced", "Balanced"],
  ["fast-cuts", "Fast cuts"],
  ["viral-short-form", "Viral short-form"],
  ["smooth-cinematic", "Smooth cinematic"],
] as const;

export const COLOR_GRADES = [
  ["natural", "Natural"],
  ["warm", "Warm"],
  ["cool", "Cool"],
  ["moody", "Moody"],
  ["bright", "Bright"],
  ["luxury-gold", "Luxury gold"],
  ["soft-pastel", "Soft pastel"],
  ["high-contrast", "High contrast"],
] as const;

export const CAPTION_STYLES = [
  ["none", "No captions"],
  ["minimal", "Minimal subtitles"],
  ["bold-viral", "Bold viral captions"],
  ["elegant", "Elegant subtitles"],
  ["corporate-lower-thirds", "Corporate lower-thirds"],
  ["karaoke", "Karaoke-style captions"],
] as const;

export const MUSIC_STYLES = [
  ["none", "No music"],
  ["romantic-piano", "Romantic piano"],
  ["corporate-uplifting", "Corporate uplifting"],
  ["cinematic", "Cinematic"],
  ["lo-fi", "Lo-fi"],
  ["energetic-beat", "Energetic beat"],
  ["soft-acoustic", "Soft acoustic"],
  ["inspirational", "Inspirational"],
  ["dramatic-trailer", "Dramatic trailer"],
] as const;

export const PLATFORM_PRESETS = {
  youtube: { label: "YouTube", aspectRatio: "16:9", resolution: "1080p", frameRate: "30fps" },
  tiktok: { label: "TikTok", aspectRatio: "9:16", resolution: "1080p", frameRate: "30fps" },
  reels: { label: "Instagram Reels", aspectRatio: "9:16", resolution: "1080p", frameRate: "30fps" },
  shorts: { label: "YouTube Shorts", aspectRatio: "9:16", resolution: "1080p", frameRate: "30fps" },
  instagram: { label: "Instagram Feed", aspectRatio: "4:5", resolution: "1080p", frameRate: "30fps" },
  facebook: { label: "Facebook", aspectRatio: "16:9", resolution: "1080p", frameRate: "30fps" },
  linkedin: { label: "LinkedIn", aspectRatio: "16:9", resolution: "1080p", frameRate: "30fps" },
  website: { label: "Website", aspectRatio: "16:9", resolution: "1080p", frameRate: "30fps" },
  presentation: { label: "Presentation", aspectRatio: "16:9", resolution: "1080p", frameRate: "30fps" },
  custom: { label: "Custom", aspectRatio: "16:9", resolution: "1080p", frameRate: "30fps" },
} as const;
