"use client";
import { useState } from "react";
type Draft = { id: string; platform: string; title: string; description: string; status: string; pricing: unknown; tags: unknown; faq: unknown };
export default function GigDraftsClient({ drafts }: { drafts: Draft[] }) {
  const [brief, setBrief] = useState(""); const [platform, setPlatform] = useState("freelancer"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function create() { setBusy(true); const response = await fetch("/api/admin/gig-drafts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ platform, brief }) }); const data = await response.json(); setBusy(false); if (response.ok) window.location.reload(); else setError(data.error || "Generation failed"); }
  async function submitted(id: string) { await fetch(`/api/admin/gig-drafts/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "SUBMITTED" }) }); window.location.reload(); }
  return <div><h1 className="text-3xl font-black">Gig drafts</h1><p className="text-muted-foreground mt-1">AI drafts copy; you review and submit it manually on the platform.</p><div className="glass border border-white/10 rounded-2xl p-6 my-8 space-y-3"><select value={platform} onChange={(e)=>setPlatform(e.target.value)} className="px-3 py-2 bg-black/20 rounded-lg"><option value="freelancer">Freelancer</option><option value="fiverr">Fiverr</option><option value="upwork">Upwork</option></select><textarea value={brief} onChange={(e)=>setBrief(e.target.value)} rows={5} placeholder="Describe the real service and deliverables" className="w-full px-3 py-2 bg-black/20 rounded-lg"/>{error && <p className="text-red-300">{error}</p>}<button disabled={busy || brief.length < 20} onClick={create} className="px-5 py-2 gold-gradient text-black font-bold rounded-lg">Generate truthful draft</button></div><div className="space-y-4">{drafts.map((draft)=><article key={draft.id} className="glass border border-white/10 rounded-2xl p-6"><div className="flex justify-between"><div className="text-xs uppercase text-gold-400">{draft.platform} · {draft.status}</div>{draft.status !== "SUBMITTED" && <button onClick={()=>submitted(draft.id)} className="text-sm">Mark manually submitted</button>}</div><h2 className="text-xl font-bold mt-2">{draft.title}</h2><p className="text-sm text-muted-foreground whitespace-pre-wrap mt-3">{draft.description}</p><details className="mt-4 text-sm"><summary>Pricing, tags, and FAQ</summary><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify({pricing:draft.pricing,tags:draft.tags,faq:draft.faq},null,2)}</pre></details></article>)}</div></div>;
}
