import { CheckCircle, Upload, CreditCard, Play, Download, WalletCards } from "lucide-react";

const STEPS = [
  { num: "01", icon: WalletCards, title: "Add Credits", desc: "Choose a one-time pack or recurring plan.", detail: ["USD catalog converted to a 15-minute IDR quote", "Admin-configured DOKU, Xendit v3, or Payoneer checkout", "Tokenized recurring cards stay gated to Xendit activation"] },
  { num: "02", icon: Upload, title: "Upload Privately", desc: "Upload video directly to private object storage.", detail: ["Multipart upload up to 10 GB", "Streaming SHA-256 in the browser", "Server verifies size, media type, and duration"] },
  { num: "03", icon: CreditCard, title: "Lock the Cost", desc: "The app calculates credits from verified duration and tier.", detail: ["Basic: 2 credits per source second", "Plus: 6 credits per source second", "Premium: 13 credits per source second"] },
  { num: "04", icon: Play, title: "Render Durably", desc: "A persistent worker submits an idempotent render attempt.", detail: ["Automatic exponential retries", "Progress and heartbeats stored in PostgreSQL", "Credits remain reserved while work is active"] },
  { num: "05", icon: CheckCircle, title: "Review the Draft", desc: "Approve the verified output or request a revision.", detail: ["The output is checked in R2 before success", "Only successful work consumes credits", "Exhausted failures create human-review alerts"] },
  { num: "06", icon: Download, title: "Download Securely", desc: "Download through a short-lived authenticated link.", detail: ["No permanent signed URLs are stored", "Raw uploads are deleted after 1 day", "Final renders are deleted after 3 days"] },
];

export default function HowItWorksPage() {
  return <div className="mx-auto max-w-4xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8 lg:py-24"><div className="mb-10 text-center sm:mb-16"><h1 className="mb-4 text-4xl font-black sm:text-5xl">How It Works</h1><p className="text-base text-muted-foreground sm:text-lg">From private upload to a verified video delivery.</p></div><div className="space-y-4 sm:space-y-8">{STEPS.map(({ num, icon: Icon, title, desc, detail }) => <div key={num} className="glass flex flex-col gap-4 rounded-2xl border border-white/5 p-5 min-[480px]:flex-row sm:gap-6 sm:p-8"><div className="gold-gradient flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-xl text-base font-black text-black sm:h-14 sm:w-14 sm:rounded-2xl sm:text-lg">{num}</div><div className="min-w-0 flex-1"><div className="mb-3 flex items-center gap-3"><Icon className="h-5 w-5 flex-shrink-0 text-gold-400" /><h2 className="text-lg font-bold sm:text-xl">{title}</h2></div><p className="mb-4 text-muted-foreground">{desc}</p><ul className="space-y-2">{detail.map((item) => <li key={item} className="flex items-start gap-2 text-sm text-muted-foreground"><CheckCircle className="mt-0.5 h-4 w-4 flex-shrink-0 text-green-500" />{item}</li>)}</ul></div></div>)}</div></div>;
}
